// ISO-4217 Country to Currency Mapping
// Maps ISO 3166-1 alpha-2 country codes to their official currencies

export interface CountryCurrencyMapping {
  countryCode: string;
  currencyCode: string;
  currencySymbol: string;
  currencyName: string;
}

export const COUNTRY_CURRENCY_MAP: Record<string, CountryCurrencyMapping> = {
  // Supported currencies (live rates available)
  US: { countryCode: "US", currencyCode: "USD", currencySymbol: "$", currencyName: "US Dollar" },
  GB: { countryCode: "GB", currencyCode: "GBP", currencySymbol: "£", currencyName: "British Pound" },
  IN: { countryCode: "IN", currencyCode: "INR", currencySymbol: "₹", currencyName: "Indian Rupee" },
  CA: { countryCode: "CA", currencyCode: "CAD", currencySymbol: "C$", currencyName: "Canadian Dollar" },
  AU: { countryCode: "AU", currencyCode: "AUD", currencySymbol: "A$", currencyName: "Australian Dollar" },
  
  // Euro countries (EUR supported)
  DE: { countryCode: "DE", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  FR: { countryCode: "FR", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  IT: { countryCode: "IT", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  ES: { countryCode: "ES", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  NL: { countryCode: "NL", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  BE: { countryCode: "BE", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  AT: { countryCode: "AT", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  PT: { countryCode: "PT", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  IE: { countryCode: "IE", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  FI: { countryCode: "FI", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  GR: { countryCode: "GR", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  LU: { countryCode: "LU", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  SI: { countryCode: "SI", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  SK: { countryCode: "SK", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  EE: { countryCode: "EE", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  LV: { countryCode: "LV", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  LT: { countryCode: "LT", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  CY: { countryCode: "CY", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  MT: { countryCode: "MT", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  MC: { countryCode: "MC", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  VA: { countryCode: "VA", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  SM: { countryCode: "SM", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  AD: { countryCode: "AD", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  ME: { countryCode: "ME", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  XK: { countryCode: "XK", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" }, // Kosovo
  
  // Other major currencies (unsupported - will fallback to USD)
  JP: { countryCode: "JP", currencyCode: "JPY", currencySymbol: "¥", currencyName: "Japanese Yen" },
  CN: { countryCode: "CN", currencyCode: "CNY", currencySymbol: "¥", currencyName: "Chinese Yuan" },
  KR: { countryCode: "KR", currencyCode: "KRW", currencySymbol: "₩", currencyName: "South Korean Won" },
  CH: { countryCode: "CH", currencyCode: "CHF", currencySymbol: "Fr", currencyName: "Swiss Franc" },
  SE: { countryCode: "SE", currencyCode: "SEK", currencySymbol: "kr", currencyName: "Swedish Krona" },
  NO: { countryCode: "NO", currencyCode: "NOK", currencySymbol: "kr", currencyName: "Norwegian Krone" },
  DK: { countryCode: "DK", currencyCode: "DKK", currencySymbol: "kr", currencyName: "Danish Krone" },
  NZ: { countryCode: "NZ", currencyCode: "NZD", currencySymbol: "NZ$", currencyName: "New Zealand Dollar" },
  SG: { countryCode: "SG", currencyCode: "SGD", currencySymbol: "S$", currencyName: "Singapore Dollar" },
  HK: { countryCode: "HK", currencyCode: "HKD", currencySymbol: "HK$", currencyName: "Hong Kong Dollar" },
  BR: { countryCode: "BR", currencyCode: "BRL", currencySymbol: "R$", currencyName: "Brazilian Real" },
  MX: { countryCode: "MX", currencyCode: "MXN", currencySymbol: "Mex$", currencyName: "Mexican Peso" },
  ZA: { countryCode: "ZA", currencyCode: "ZAR", currencySymbol: "R", currencyName: "South African Rand" },
  RU: { countryCode: "RU", currencyCode: "RUB", currencySymbol: "₽", currencyName: "Russian Ruble" },
  TR: { countryCode: "TR", currencyCode: "TRY", currencySymbol: "₺", currencyName: "Turkish Lira" },
  PL: { countryCode: "PL", currencyCode: "PLN", currencySymbol: "zł", currencyName: "Polish Zloty" },
  TH: { countryCode: "TH", currencyCode: "THB", currencySymbol: "฿", currencyName: "Thai Baht" },
  MY: { countryCode: "MY", currencyCode: "MYR", currencySymbol: "RM", currencyName: "Malaysian Ringgit" },
  ID: { countryCode: "ID", currencyCode: "IDR", currencySymbol: "Rp", currencyName: "Indonesian Rupiah" },
  PH: { countryCode: "PH", currencyCode: "PHP", currencySymbol: "₱", currencyName: "Philippine Peso" },
  VN: { countryCode: "VN", currencyCode: "VND", currencySymbol: "₫", currencyName: "Vietnamese Dong" },
  PK: { countryCode: "PK", currencyCode: "PKR", currencySymbol: "Rs", currencyName: "Pakistani Rupee" },
  BD: { countryCode: "BD", currencyCode: "BDT", currencySymbol: "৳", currencyName: "Bangladeshi Taka" },
  EG: { countryCode: "EG", currencyCode: "EGP", currencySymbol: "E£", currencyName: "Egyptian Pound" },
  NG: { countryCode: "NG", currencyCode: "NGN", currencySymbol: "₦", currencyName: "Nigerian Naira" },
  AR: { countryCode: "AR", currencyCode: "ARS", currencySymbol: "$", currencyName: "Argentine Peso" },
  CL: { countryCode: "CL", currencyCode: "CLP", currencySymbol: "$", currencyName: "Chilean Peso" },
  CO: { countryCode: "CO", currencyCode: "COP", currencySymbol: "$", currencyName: "Colombian Peso" },
  PE: { countryCode: "PE", currencyCode: "PEN", currencySymbol: "S/", currencyName: "Peruvian Sol" },
  IL: { countryCode: "IL", currencyCode: "ILS", currencySymbol: "₪", currencyName: "Israeli Shekel" },
  AE: { countryCode: "AE", currencyCode: "AED", currencySymbol: "د.إ", currencyName: "UAE Dirham" },
  SA: { countryCode: "SA", currencyCode: "SAR", currencySymbol: "﷼", currencyName: "Saudi Riyal" },
  CZ: { countryCode: "CZ", currencyCode: "CZK", currencySymbol: "Kč", currencyName: "Czech Koruna" },
  HU: { countryCode: "HU", currencyCode: "HUF", currencySymbol: "Ft", currencyName: "Hungarian Forint" },
  RO: { countryCode: "RO", currencyCode: "RON", currencySymbol: "lei", currencyName: "Romanian Leu" },
  IS: { countryCode: "IS", currencyCode: "ISK", currencySymbol: "kr", currencyName: "Icelandic Króna" },
  HR: { countryCode: "HR", currencyCode: "EUR", currencySymbol: "€", currencyName: "Euro" },
  RS: { countryCode: "RS", currencyCode: "RSD", currencySymbol: "din", currencyName: "Serbian Dinar" },
  UA: { countryCode: "UA", currencyCode: "UAH", currencySymbol: "₴", currencyName: "Ukrainian Hryvnia" },
  KZ: { countryCode: "KZ", currencyCode: "KZT", currencySymbol: "₸", currencyName: "Kazakhstani Tenge" },
  KE: { countryCode: "KE", currencyCode: "KES", currencySymbol: "KSh", currencyName: "Kenyan Shilling" },
  GH: { countryCode: "GH", currencyCode: "GHS", currencySymbol: "₵", currencyName: "Ghanaian Cedi" },
  UG: { countryCode: "UG", currencyCode: "UGX", currencySymbol: "USh", currencyName: "Ugandan Shilling" },
  TZ: { countryCode: "TZ", currencyCode: "TZS", currencySymbol: "TSh", currencyName: "Tanzanian Shilling" },
  
  // Rest of countries - USD fallback
  AF: { countryCode: "AF", currencyCode: "AFN", currencySymbol: "؋", currencyName: "Afghan Afghani" },
  AL: { countryCode: "AL", currencyCode: "ALL", currencySymbol: "L", currencyName: "Albanian Lek" },
  DZ: { countryCode: "DZ", currencyCode: "DZD", currencySymbol: "د.ج", currencyName: "Algerian Dinar" },
  AO: { countryCode: "AO", currencyCode: "AOA", currencySymbol: "Kz", currencyName: "Angolan Kwanza" },
  AG: { countryCode: "AG", currencyCode: "XCD", currencySymbol: "$", currencyName: "East Caribbean Dollar" },
  AM: { countryCode: "AM", currencyCode: "AMD", currencySymbol: "֏", currencyName: "Armenian Dram" },
  AZ: { countryCode: "AZ", currencyCode: "AZN", currencySymbol: "₼", currencyName: "Azerbaijani Manat" },
  BS: { countryCode: "BS", currencyCode: "BSD", currencySymbol: "$", currencyName: "Bahamian Dollar" },
  BH: { countryCode: "BH", currencyCode: "BHD", currencySymbol: ".د.ب", currencyName: "Bahraini Dinar" },
  BB: { countryCode: "BB", currencyCode: "BBD", currencySymbol: "$", currencyName: "Barbadian Dollar" },
  BY: { countryCode: "BY", currencyCode: "BYN", currencySymbol: "Br", currencyName: "Belarusian Ruble" },
  BZ: { countryCode: "BZ", currencyCode: "BZD", currencySymbol: "$", currencyName: "Belize Dollar" },
  BJ: { countryCode: "BJ", currencyCode: "XOF", currencySymbol: "Fr", currencyName: "West African CFA Franc" },
  BT: { countryCode: "BT", currencyCode: "BTN", currencySymbol: "Nu.", currencyName: "Bhutanese Ngultrum" },
  BO: { countryCode: "BO", currencyCode: "BOB", currencySymbol: "Bs.", currencyName: "Bolivian Boliviano" },
  BA: { countryCode: "BA", currencyCode: "BAM", currencySymbol: "KM", currencyName: "Bosnia-Herzegovina Mark" },
  BW: { countryCode: "BW", currencyCode: "BWP", currencySymbol: "P", currencyName: "Botswana Pula" },
  BN: { countryCode: "BN", currencyCode: "BND", currencySymbol: "$", currencyName: "Brunei Dollar" },
  BG: { countryCode: "BG", currencyCode: "BGN", currencySymbol: "лв", currencyName: "Bulgarian Lev" },
  BF: { countryCode: "BF", currencyCode: "XOF", currencySymbol: "Fr", currencyName: "West African CFA Franc" },
  BI: { countryCode: "BI", currencyCode: "BIF", currencySymbol: "Fr", currencyName: "Burundian Franc" },
  CV: { countryCode: "CV", currencyCode: "CVE", currencySymbol: "$", currencyName: "Cape Verdean Escudo" },
  KH: { countryCode: "KH", currencyCode: "KHR", currencySymbol: "៛", currencyName: "Cambodian Riel" },
  CM: { countryCode: "CM", currencyCode: "XAF", currencySymbol: "Fr", currencyName: "Central African CFA Franc" },
  CF: { countryCode: "CF", currencyCode: "XAF", currencySymbol: "Fr", currencyName: "Central African CFA Franc" },
  TD: { countryCode: "TD", currencyCode: "XAF", currencySymbol: "Fr", currencyName: "Central African CFA Franc" },
  CG: { countryCode: "CG", currencyCode: "XAF", currencySymbol: "Fr", currencyName: "Central African CFA Franc" },
  CD: { countryCode: "CD", currencyCode: "CDF", currencySymbol: "Fr", currencyName: "Congolese Franc" },
  CR: { countryCode: "CR", currencyCode: "CRC", currencySymbol: "₡", currencyName: "Costa Rican Colón" },
  CI: { countryCode: "CI", currencyCode: "XOF", currencySymbol: "Fr", currencyName: "West African CFA Franc" },
  CU: { countryCode: "CU", currencyCode: "CUP", currencySymbol: "$", currencyName: "Cuban Peso" },
  DJ: { countryCode: "DJ", currencyCode: "DJF", currencySymbol: "Fr", currencyName: "Djiboutian Franc" },
  DM: { countryCode: "DM", currencyCode: "XCD", currencySymbol: "$", currencyName: "East Caribbean Dollar" },
  DO: { countryCode: "DO", currencyCode: "DOP", currencySymbol: "$", currencyName: "Dominican Peso" },
  EC: { countryCode: "EC", currencyCode: "USD", currencySymbol: "$", currencyName: "US Dollar" },
  SV: { countryCode: "SV", currencyCode: "USD", currencySymbol: "$", currencyName: "US Dollar" },
  GQ: { countryCode: "GQ", currencyCode: "XAF", currencySymbol: "Fr", currencyName: "Central African CFA Franc" },
  ER: { countryCode: "ER", currencyCode: "ERN", currencySymbol: "Nfk", currencyName: "Eritrean Nakfa" },
  SZ: { countryCode: "SZ", currencyCode: "SZL", currencySymbol: "L", currencyName: "Swazi Lilangeni" },
  ET: { countryCode: "ET", currencyCode: "ETB", currencySymbol: "Br", currencyName: "Ethiopian Birr" },
  FJ: { countryCode: "FJ", currencyCode: "FJD", currencySymbol: "$", currencyName: "Fijian Dollar" },
  GA: { countryCode: "GA", currencyCode: "XAF", currencySymbol: "Fr", currencyName: "Central African CFA Franc" },
  GM: { countryCode: "GM", currencyCode: "GMD", currencySymbol: "D", currencyName: "Gambian Dalasi" },
  GE: { countryCode: "GE", currencyCode: "GEL", currencySymbol: "₾", currencyName: "Georgian Lari" },
  GD: { countryCode: "GD", currencyCode: "XCD", currencySymbol: "$", currencyName: "East Caribbean Dollar" },
  GT: { countryCode: "GT", currencyCode: "GTQ", currencySymbol: "Q", currencyName: "Guatemalan Quetzal" },
  GN: { countryCode: "GN", currencyCode: "GNF", currencySymbol: "Fr", currencyName: "Guinean Franc" },
  GW: { countryCode: "GW", currencyCode: "XOF", currencySymbol: "Fr", currencyName: "West African CFA Franc" },
  GY: { countryCode: "GY", currencyCode: "GYD", currencySymbol: "$", currencyName: "Guyanese Dollar" },
  HT: { countryCode: "HT", currencyCode: "HTG", currencySymbol: "G", currencyName: "Haitian Gourde" },
  HN: { countryCode: "HN", currencyCode: "HNL", currencySymbol: "L", currencyName: "Honduran Lempira" },
  IR: { countryCode: "IR", currencyCode: "IRR", currencySymbol: "﷼", currencyName: "Iranian Rial" },
  IQ: { countryCode: "IQ", currencyCode: "IQD", currencySymbol: "ع.د", currencyName: "Iraqi Dinar" },
  JM: { countryCode: "JM", currencyCode: "JMD", currencySymbol: "$", currencyName: "Jamaican Dollar" },
  JO: { countryCode: "JO", currencyCode: "JOD", currencySymbol: "د.ا", currencyName: "Jordanian Dinar" },
  KI: { countryCode: "KI", currencyCode: "AUD", currencySymbol: "A$", currencyName: "Australian Dollar" },
  KW: { countryCode: "KW", currencyCode: "KWD", currencySymbol: "د.ك", currencyName: "Kuwaiti Dinar" },
  KG: { countryCode: "KG", currencyCode: "KGS", currencySymbol: "с", currencyName: "Kyrgyzstani Som" },
  LA: { countryCode: "LA", currencyCode: "LAK", currencySymbol: "₭", currencyName: "Lao Kip" },
  LB: { countryCode: "LB", currencyCode: "LBP", currencySymbol: "ل.ل", currencyName: "Lebanese Pound" },
  LS: { countryCode: "LS", currencyCode: "LSL", currencySymbol: "L", currencyName: "Lesotho Loti" },
  LR: { countryCode: "LR", currencyCode: "LRD", currencySymbol: "$", currencyName: "Liberian Dollar" },
  LY: { countryCode: "LY", currencyCode: "LYD", currencySymbol: "ل.د", currencyName: "Libyan Dinar" },
  LI: { countryCode: "LI", currencyCode: "CHF", currencySymbol: "Fr", currencyName: "Swiss Franc" },
  MG: { countryCode: "MG", currencyCode: "MGA", currencySymbol: "Ar", currencyName: "Malagasy Ariary" },
  MW: { countryCode: "MW", currencyCode: "MWK", currencySymbol: "MK", currencyName: "Malawian Kwacha" },
  MV: { countryCode: "MV", currencyCode: "MVR", currencySymbol: "ރ.", currencyName: "Maldivian Rufiyaa" },
  ML: { countryCode: "ML", currencyCode: "XOF", currencySymbol: "Fr", currencyName: "West African CFA Franc" },
  MH: { countryCode: "MH", currencyCode: "USD", currencySymbol: "$", currencyName: "US Dollar" },
  MR: { countryCode: "MR", currencyCode: "MRU", currencySymbol: "UM", currencyName: "Mauritanian Ouguiya" },
  MU: { countryCode: "MU", currencyCode: "MUR", currencySymbol: "₨", currencyName: "Mauritian Rupee" },
  FM: { countryCode: "FM", currencyCode: "USD", currencySymbol: "$", currencyName: "US Dollar" },
  MD: { countryCode: "MD", currencyCode: "MDL", currencySymbol: "L", currencyName: "Moldovan Leu" },
  MN: { countryCode: "MN", currencyCode: "MNT", currencySymbol: "₮", currencyName: "Mongolian Tögrög" },
  MA: { countryCode: "MA", currencyCode: "MAD", currencySymbol: "د.م.", currencyName: "Moroccan Dirham" },
  MZ: { countryCode: "MZ", currencyCode: "MZN", currencySymbol: "MT", currencyName: "Mozambican Metical" },
  MM: { countryCode: "MM", currencyCode: "MMK", currencySymbol: "K", currencyName: "Myanmar Kyat" },
  NA: { countryCode: "NA", currencyCode: "NAD", currencySymbol: "$", currencyName: "Namibian Dollar" },
  NR: { countryCode: "NR", currencyCode: "AUD", currencySymbol: "A$", currencyName: "Australian Dollar" },
  NP: { countryCode: "NP", currencyCode: "NPR", currencySymbol: "₨", currencyName: "Nepalese Rupee" },
  NI: { countryCode: "NI", currencyCode: "NIO", currencySymbol: "C$", currencyName: "Nicaraguan Córdoba" },
  NE: { countryCode: "NE", currencyCode: "XOF", currencySymbol: "Fr", currencyName: "West African CFA Franc" },
  KP: { countryCode: "KP", currencyCode: "KPW", currencySymbol: "₩", currencyName: "North Korean Won" },
  MK: { countryCode: "MK", currencyCode: "MKD", currencySymbol: "ден", currencyName: "Macedonian Denar" },
  OM: { countryCode: "OM", currencyCode: "OMR", currencySymbol: "ر.ع.", currencyName: "Omani Rial" },
  PW: { countryCode: "PW", currencyCode: "USD", currencySymbol: "$", currencyName: "US Dollar" },
  PS: { countryCode: "PS", currencyCode: "ILS", currencySymbol: "₪", currencyName: "Israeli Shekel" },
  PA: { countryCode: "PA", currencyCode: "PAB", currencySymbol: "B/.", currencyName: "Panamanian Balboa" },
  PG: { countryCode: "PG", currencyCode: "PGK", currencySymbol: "K", currencyName: "Papua New Guinean Kina" },
  PY: { countryCode: "PY", currencyCode: "PYG", currencySymbol: "₲", currencyName: "Paraguayan Guaraní" },
  QA: { countryCode: "QA", currencyCode: "QAR", currencySymbol: "ر.ق", currencyName: "Qatari Riyal" },
  RW: { countryCode: "RW", currencyCode: "RWF", currencySymbol: "Fr", currencyName: "Rwandan Franc" },
  KN: { countryCode: "KN", currencyCode: "XCD", currencySymbol: "$", currencyName: "East Caribbean Dollar" },
  LC: { countryCode: "LC", currencyCode: "XCD", currencySymbol: "$", currencyName: "East Caribbean Dollar" },
  VC: { countryCode: "VC", currencyCode: "XCD", currencySymbol: "$", currencyName: "East Caribbean Dollar" },
  WS: { countryCode: "WS", currencyCode: "WST", currencySymbol: "T", currencyName: "Samoan Tālā" },
  ST: { countryCode: "ST", currencyCode: "STN", currencySymbol: "Db", currencyName: "São Tomé and Príncipe Dobra" },
  SN: { countryCode: "SN", currencyCode: "XOF", currencySymbol: "Fr", currencyName: "West African CFA Franc" },
  SC: { countryCode: "SC", currencyCode: "SCR", currencySymbol: "₨", currencyName: "Seychellois Rupee" },
  SL: { countryCode: "SL", currencyCode: "SLL", currencySymbol: "Le", currencyName: "Sierra Leonean Leone" },
  SB: { countryCode: "SB", currencyCode: "SBD", currencySymbol: "$", currencyName: "Solomon Islands Dollar" },
  SO: { countryCode: "SO", currencyCode: "SOS", currencySymbol: "Sh", currencyName: "Somali Shilling" },
  SS: { countryCode: "SS", currencyCode: "SSP", currencySymbol: "£", currencyName: "South Sudanese Pound" },
  LK: { countryCode: "LK", currencyCode: "LKR", currencySymbol: "Rs", currencyName: "Sri Lankan Rupee" },
  SD: { countryCode: "SD", currencyCode: "SDG", currencySymbol: "ج.س.", currencyName: "Sudanese Pound" },
  SR: { countryCode: "SR", currencyCode: "SRD", currencySymbol: "$", currencyName: "Surinamese Dollar" },
  SY: { countryCode: "SY", currencyCode: "SYP", currencySymbol: "£", currencyName: "Syrian Pound" },
  TJ: { countryCode: "TJ", currencyCode: "TJS", currencySymbol: "ЅМ", currencyName: "Tajikistani Somoni" },
  TL: { countryCode: "TL", currencyCode: "USD", currencySymbol: "$", currencyName: "US Dollar" },
  TG: { countryCode: "TG", currencyCode: "XOF", currencySymbol: "Fr", currencyName: "West African CFA Franc" },
  TO: { countryCode: "TO", currencyCode: "TOP", currencySymbol: "T$", currencyName: "Tongan Paʻanga" },
  TT: { countryCode: "TT", currencyCode: "TTD", currencySymbol: "$", currencyName: "Trinidad and Tobago Dollar" },
  TN: { countryCode: "TN", currencyCode: "TND", currencySymbol: "د.ت", currencyName: "Tunisian Dinar" },
  TM: { countryCode: "TM", currencyCode: "TMT", currencySymbol: "m", currencyName: "Turkmenistani Manat" },
  TV: { countryCode: "TV", currencyCode: "AUD", currencySymbol: "A$", currencyName: "Australian Dollar" },
  UY: { countryCode: "UY", currencyCode: "UYU", currencySymbol: "$", currencyName: "Uruguayan Peso" },
  UZ: { countryCode: "UZ", currencyCode: "UZS", currencySymbol: "so'm", currencyName: "Uzbekistani Som" },
  VU: { countryCode: "VU", currencyCode: "VUV", currencySymbol: "Vt", currencyName: "Vanuatu Vatu" },
  VE: { countryCode: "VE", currencyCode: "VES", currencySymbol: "Bs.S", currencyName: "Venezuelan Bolívar" },
  YE: { countryCode: "YE", currencyCode: "YER", currencySymbol: "﷼", currencyName: "Yemeni Rial" },
  ZM: { countryCode: "ZM", currencyCode: "ZMW", currencySymbol: "ZK", currencyName: "Zambian Kwacha" },
  ZW: { countryCode: "ZW", currencyCode: "ZWL", currencySymbol: "$", currencyName: "Zimbabwean Dollar" },
};

// Currencies that have live exchange rate support
export const SUPPORTED_CURRENCIES = ["USD", "GBP", "INR", "CAD", "AUD", "EUR"];

// Helper to get currency info for a country
export function getCurrencyForCountry(countryCode: string): CountryCurrencyMapping {
  const mapping = COUNTRY_CURRENCY_MAP[countryCode];
  if (mapping) return mapping;
  
  // Fallback to USD if country not found
  return {
    countryCode,
    currencyCode: "USD",
    currencySymbol: "$",
    currencyName: "US Dollar",
  };
}

// Helper to check if a currency is supported with live rates
export function isCurrencySupported(currencyCode: string): boolean {
  return SUPPORTED_CURRENCIES.includes(currencyCode);
}

// Helper to get fallback currency if not supported
export function getEffectiveCurrency(countryCurrencyCode: string): string {
  return isCurrencySupported(countryCurrencyCode) ? countryCurrencyCode : "USD";
}
