export const COUNTRY_STATES: Record<string, string[]> = {
  US: [
    "Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"
  ],
  IN: [
    "Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chhattisgarh","Goa","Gujarat","Haryana","Himachal Pradesh","Jharkhand","Karnataka","Kerala","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Punjab","Rajasthan","Sikkim","Tamil Nadu","Telangana","Tripura","Uttar Pradesh","Uttarakhand","West Bengal","Delhi","Jammu and Kashmir","Ladakh"
  ],
  CA: [
    "Alberta","British Columbia","Manitoba","New Brunswick","Newfoundland and Labrador","Nova Scotia","Ontario","Prince Edward Island","Quebec","Saskatchewan","Northwest Territories","Nunavut","Yukon"
  ],
  AU: [
    "New South Wales","Queensland","South Australia","Tasmania","Victoria","Western Australia","Australian Capital Territory","Northern Territory"
  ],
  DE: [
    "Baden-Württemberg","Bavaria","Berlin","Brandenburg","Bremen","Hamburg","Hesse","Lower Saxony","Mecklenburg-Vorpommern","North Rhine-Westphalia","Rhineland-Palatinate","Saarland","Saxony","Saxony-Anhalt","Schleswig-Holstein","Thuringia"
  ],
  FR: [
    "Auvergne-Rhône-Alpes","Bourgogne-Franche-Comté","Brittany","Centre-Val de Loire","Corsica","Grand Est","Hauts-de-France","Île-de-France","Normandy","Nouvelle-Aquitaine","Occitanie","Pays de la Loire","Provence-Alpes-Côte d'Azur"
  ],
  UK: [
    "England","Scotland","Wales","Northern Ireland"
  ],
};

// State to Cities mapping - major cities for each state/region
export const STATE_CITIES: Record<string, string[]> = {
  // US Cities
  "California": ["Los Angeles", "San Francisco", "San Diego", "Sacramento", "Fresno", "Long Beach", "Oakland", "Bakersfield", "Anaheim", "Santa Ana"],
  "Texas": ["Houston", "Dallas", "Austin", "San Antonio", "Fort Worth", "El Paso", "Arlington", "Corpus Christi", "Plano", "Laredo"],
  "Florida": ["Jacksonville", "Miami", "Tampa", "Orlando", "St. Petersburg", "Hialeah", "Fort Lauderdale", "Tallahassee", "Port St. Lucie", "Cape Coral"],
  "New York": ["New York City", "Buffalo", "Rochester", "Yonkers", "Syracuse", "Albany", "New Rochelle", "Mount Vernon", "Schenectady", "Utica"],
  "Pennsylvania": ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading", "Scranton", "Bethlehem", "Lancaster", "Harrisburg", "Altoona"],
  "Illinois": ["Chicago", "Aurora", "Rockford", "Joliet", "Naperville", "Springfield", "Peoria", "Elgin", "Waukegan", "Cicero"],
  "Ohio": ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton", "Parma", "Canton", "Youngstown", "Hamilton"],
  "Georgia": ["Atlanta", "Columbus", "Savannah", "Augusta", "Athens", "Sandy Springs", "Marietta", "Alpharetta", "Roswell", "Johns Creek"],
  "North Carolina": ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem", "Fayetteville", "Cary", "Wilmington", "High Point", "Greenville"],
  "Michigan": ["Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Lansing", "Ann Arbor", "Flint", "Dearborn", "Livonia", "Kalamazoo"],
  "Arizona": ["Phoenix", "Mesa", "Chandler", "Scottsdale", "Glendale", "Gilbert", "Tempe", "Peoria", "Surprise", "Avondale"],
  "Tennessee": ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville", "Murfreesboro", "Franklin", "Jackson", "Hendersonville", "Smyrna"],
  "Virginia": ["Virginia Beach", "Norfolk", "Richmond", "Alexandria", "Arlington", "Roanoke", "Newport News", "Hampton", "Lynchburg", "Blacksburg"],
  "Washington": ["Seattle", "Tacoma", "Vancouver", "Bellevue", "Kent", "Everett", "Renton", "Federal Way", "Kirkland", "Sammamish"],
  "Massachusetts": ["Boston", "Worcester", "Springfield", "Lowell", "Cambridge", "New Bedford", "Brockton", "Quincy", "Lynn", "Fall River"],
  "Indiana": ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Bloomington", "Carmel", "Fishers", "Muncie", "Lafayette", "Terre Haute"],
  "Maryland": ["Baltimore", "Frederick", "Gaithersburg", "Bowie", "Annapolis", "College Park", "Salisbury", "Hyattsville", "Laurel", "Towson"],
  "Missouri": ["Kansas City", "St. Louis", "Springfield", "Independence", "Columbia", "Lee's Summit", "O'Fallon", "Saint Charles", "Saint Peters", "Florissant"],
  "Wisconsin": ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine", "Appleton", "Waukesha", "Eau Claire", "Oshkosh", "Janesville"],
  "Colorado": ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood", "Thornton", "Arvada", "Westminster", "Pueblo", "Greeley"],
  "Minnesota": ["Minneapolis", "St. Paul", "Rochester", "Duluth", "St. Cloud", "Bloomington", "Coon Rapids", "Maple Grove", "Plymouth", "Eagan"],
  "Oklahoma": ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Edmond", "Lawton", "Moore", "Midwest City", "Enid", "Bartlesville"],
  "Louisiana": ["New Orleans", "Baton Rouge", "Shreveport", "Metairie", "Lafayette", "Lake Charles", "Kenner", "Alexandria", "Monroe", "Houma"],
  "Kentucky": ["Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington", "Hopkinsville", "Richmond", "Frankfort", "Paducah", "Corbin"],
  "Alabama": ["Birmingham", "Montgomery", "Mobile", "Huntsville", "Tuscaloosa", "Hoover", "Dothan", "Auburn", "Anniston", "Bessemer"],
  "New Jersey": ["Newark", "Jersey City", "Paterson", "Elizabeth", "Trenton", "Edison", "Clifton", "Camden", "Irvington", "Passaic"],
  "Arkansas": ["Little Rock", "Fort Smith", "Fayetteville", "Springdale", "Jonesboro", "North Little Rock", "Bentonville", "Pine Bluff", "Conway", "Texarkana"],
  "Kansas": ["Wichita", "Overland Park", "Kansas City", "Topeka", "Olathe", "Lawrence", "Shawnee", "Leawood", "Lenexa", "Salina"],
  "Utah": ["Salt Lake City", "Provo", "West Valley City", "Ogden", "Sandy", "Orem", "St. George", "Layton", "Lehi", "Millcreek"],
  "Iowa": ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City", "Waterloo", "Council Bluffs", "Dubuque", "Ames", "Bettendorf"],
  "Nevada": ["Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks", "Elko", "Carson City", "Boulder City", "West Wendover", "Laughlin"],
  "Mississippi": ["Jackson", "Gulfport", "Southaven", "Biloxi", "Hattiesburg", "Tupelo", "Meridian", "Olive Branch", "Greenville", "Vicksburg"],
  "Connecticut": ["Bridgeport", "New Haven", "Waterbury", "Hartford", "Stamford", "Norwalk", "Danbury", "New Britain", "Bristol", "Meriden"],
  "Oregon": ["Portland", "Eugene", "Salem", "Gresham", "Hillsboro", "Beaverton", "Bend", "Medford", "Springfield", "Corvallis"],
  "New Mexico": ["Albuquerque", "Las Cruces", "Santa Fe", "Rio Rancho", "Roswell", "Clovis", "Farmington", "Silver City", "Hobbs", "Gallup"],
  "West Virginia": ["Charleston", "Huntington", "Parkersburg", "Morgantown", "Wheeling", "Weirton", "Fairmont", "Beckley", "Lewisburg", "Bluefield"],
  "Hawaii": ["Honolulu", "Hilo", "Kailua", "Kaneohe", "Waipahu", "Pearl City", "Mililani", "Wailuku", "Kihei", "Kahaluu"],
  "Idaho": ["Boise", "Nampa", "Meridian", "Pocatello", "Coeur d'Alene", "Twin Falls", "Lewiston", "Moscow", "Caldwell", "Post Falls"],
  "South Carolina": ["Charleston", "Columbia", "Greenville", "North Charleston", "Summerville", "Myrtle Beach", "Spartanburg", "Rock Hill", "Beaufort", "Goose Creek"],
  "South Dakota": ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Watertown", "Mitchell", "Yankton", "Huron", "Pierre", "Spearfish"],
  "Montana": ["Billings", "Missoula", "Great Falls", "Bozeman", "Butte", "Helena", "Kalispell", "Havre", "Anaconda", "Miles City"],
  "North Dakota": ["Bismarck", "Fargo", "Grand Forks", "Minot", "Williston", "Mandan", "Dickinson", "Jamestown", "Watford City", "Devils Lake"],
  "Nebraska": ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney", "Fremont", "Hastings", "North Platte", "Norfolk", "Papillion"],
  "Alaska": ["Anchorage", "Juneau", "Fairbanks", "Sitka", "Ketchikan", "Wasilla", "Kenai", "Tanana", "Bethel", "Barrow"],
  "Maine": ["Portland", "Lewiston", "Bangor", "South Portland", "Auburn", "Augusta", "Waterville", "Westbrook", "Presque Isle", "Calais"],
  "New Hampshire": ["Manchester", "Nashua", "Concord", "Derry", "Portsmouth", "Rochester", "Salem", "Merrimack", "Keene", "Laconia"],
  "Rhode Island": ["Providence", "Warwick", "Cranston", "Pawtucket", "East Providence", "Woonsocket", "Coventry", "North Providence", "Central Falls", "Johnston"],
  "Vermont": ["Burlington", "Rutland", "South Burlington", "Colchester", "Montpelier", "Barre", "Brattleboro", "Middlebury", "Bennington", "Winooski"],
  "Wyoming": ["Cheyenne", "Casper", "Laramie", "Gillette", "Sheridan", "Rock Springs", "Cody", "Evanston", "Rawlins", "Powell"],

  // India Cities - State wise
  "Maharashtra": ["Mumbai", "Pune", "Nagpur", "Thane", "Nashik", "Aurangabad", "Solapur", "Kolhapur", "Sangli", "Amravati"],
  "Delhi": ["New Delhi", "Delhi Cantonment", "West Delhi", "East Delhi", "North Delhi", "South Delhi", "Central Delhi"],
  "Karnataka": ["Bangalore", "Mysore", "Mangalore", "Belgaum", "Gulbarga", "Udupi", "Shimoga", "Tumkur", "Bijapur", "Chikmagalur"],
  "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Salem", "Tiruchirappalli", "Tiruppur", "Erode", "Thanjavur", "Nagercoil", "Vellore"],
  "Uttar Pradesh": ["Lucknow", "Kanpur", "Varanasi", "Agra", "Meerut", "Allahabad", "Bareilly", "Ghaziabad", "Noida", "Gorakhpur"],
  "West Bengal": ["Kolkata", "Darjeeling", "Siliguri", "Durgapur", "Asansol", "Burdwan", "Hooghly", "Murshidabad", "Birbhum", "Malda"],
  "Gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Jamnagar", "Junagadh", "Bhavnagar", "Anand", "Gandhinagar", "Vapi"],
  "Rajasthan": ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Bikaner", "Ajmer", "Alwar", "Bhilwara", "Pali", "Sikar"],
  "Punjab": ["Chandigarh", "Amritsar", "Ludhiana", "Jalandhar", "Patiala", "Bathinda", "Mohali", "Hoshiarpur", "Faridkot", "Gurdaspur"],
  "Madhya Pradesh": ["Bhopal", "Indore", "Gwalior", "Jabalpur", "Ujjain", "Sehore", "Dewas", "Khargo", "Satna", "Ratlam"],
  "Andhra Pradesh": ["Hyderabad", "Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Tenali", "Rajahmundry", "Tirupati", "Anantapur", "Kadapa"],
  "Telangana": ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Ramagundam", "Khammam", "Mahbubnagar", "Medak", "Adilabad", "Siddipet"],
  "Kerala": ["Kochi", "Thiruvananthapuram", "Kozhikode", "Thrissur", "Alappuzha", "Kannur", "Kollam", "Pathanamthitta", "Ernakulam", "Malappuram"],
  "Haryana": ["Faridabad", "Gurgaon", "Hisar", "Rohtak", "Panipat", "Ambala", "Yamuna Nagar", "Sonipat", "Karnal", "Jhajjar"],
  "Himachal Pradesh": ["Shimla", "Mandi", "Solan", "Palampur", "Kangra", "Nahan", "Bilaspur", "Hamirpur", "Dharamshala", "Chamba"],
  "Assam": ["Guwahati", "Silchar", "Dibrugadh", "Nagaon", "Tinsukia", "Barpeta", "Jorhat", "Lakhimpur", "Sonitpur", "Bongaigaon"],
  "Goa": ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda", "Pernem", "Sattari", "Bicholim", "Sanquelim", "Canacona"],
  "Odisha": ["Bhubaneswar", "Cuttack", "Rourkela", "Brahmapur", "Sambalpur", "Balasore", "Bargarh", "Jharsuguda", "Angul", "Jajpur"],
  "Jharkhand": ["Ranchi", "Dhanbad", "Giridih", "Jamshedpur", "Bokaro", "Deoghar", "Hazaribagh", "Medininagar", "Daltonganj", "Koderma"],
  "Chhattisgarh": ["Raipur", "Bhilai", "Durg", "Rajnandgaon", "Bilaspur", "Korba", "Raigarh", "Jagdalpur", "Dhamtari", "Mandir"],
  "Bihar": ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Purnia", "Darbhanga", "Madhubani", "Siwan", "East Champaran", "Vaishali"],
  "Manipur": ["Imphal", "Imphal West", "Imphal East", "Thoubal", "Ukhrul", "Tamenglong", "Churachandpur", "Bishnupur", "Kakching", "Jiribam"],
  "Meghalaya": ["Shillong", "Tura", "Jowai", "Nongstoin", "Baghmara", "Khliehriat", "Mairang", "Sohrarim", "Resubelpara", "Garo Hills"],
  "Mizoram": ["Aizawl", "Lunglei", "Saiha", "Champhai", "Serchhip", "Kolasib", "Lawngtlai", "Mamit", "Saitual", "Khawzawl"],
  "Nagaland": ["Kohima", "Dimapur", "Mokokchung", "Tuensang", "Zunheboto", "Phek", "Wokha", "Kiphire", "Mon", "Longleng"],
  "Sikkim": ["Gangtok", "Namchi", "Gyalshing", "Mangan", "Pelling", "Lachung", "Ravangla", "Soreng", "Dentam", "Yuksom"],
  "Tripura": ["Agartala", "Udaipur", "Dharmanagar", "Kailashahar", "Ambassa", "Sabroom", "Jirania", "Khowai", "Tepania", "Unakoti"],
  "Arunachal Pradesh": ["Itanagar", "Naharlagun", "Pasighat", "Tezu", "Ziro", "Bomdila", "Roing", "Changlang", "Lohit", "Papum Pare"],
  "Uttarakhand": ["Dehradun", "Haridwar", "Nainital", "Roorkee", "Rudraprayag", "Srinagar", "Pauri", "Almora", "Bageshwar", "Champawat"],
  "Puducherry": ["Puducherry", "Yanam", "Mahe", "Karaikal"],
  "Lakshadweep": ["Kavaratti", "Agatti", "Minicoy"],
  "Andaman and Nicobar Islands": ["Port Blair", "Car Nicobar", "Campbell Bay", "Rangat", "Mayabunder", "Havelock Island", "Neil Island", "Diglipur"],

  // Canada Cities
  "Ontario": ["Toronto", "Ottawa", "Hamilton", "London", "Mississauga", "Brampton", "Kitchener", "Markham", "Waterloo", "Windsor"],
  "Quebec": ["Montreal", "Quebec City", "Gatineau", "Laval", "Sherbrooke", "Trois-Rivières", "Longueuil", "Saint-Jérôme", "Lachine", "Lévis"],
  "British Columbia": ["Vancouver", "Victoria", "Surrey", "Burnaby", "Coquitlam", "Kelowna", "Abbotsford", "Langley", "Kamloops", "Nanaimo"],
  "Alberta": ["Calgary", "Edmonton", "Red Deer", "Lethbridge", "Medicine Hat", "Airdrie", "Chestermere", "Grande Prairie", "Spruce Grove", "St. Albert"],
  "Manitoba": ["Winnipeg", "Brandon", "Flin Flon", "Portage la Prairie", "Dauphin", "Thompson", "The Pas", "Selkirk", "Morden", "Winkler"],
  "Saskatchewan": ["Saskatoon", "Regina", "Prince Albert", "Moose Jaw", "Yorkton", "Swift Current", "North Battleford", "Lloydminster", "Melfort", "Humboldt"],
  "Nova Scotia": ["Halifax", "Cape Breton", "Glace Bay", "New Glasgow", "Truro", "Bridgewater", "Yarmouth", "Kentville", "Amherst", "Sydney"],
  "New Brunswick": ["Saint John", "Moncton", "Fredericton", "Saint-Jean", "Bathurst", "Campbellton", "Edmundston", "Newcastle", "Sackville", "Miramichi"],
  "Newfoundland and Labrador": ["St. John's", "Corner Brook", "Gander", "Thompson", "Grand Falls-Windsor", "Happy Valley-Goose Bay", "Labrador City", "Port aux Basques", "Twillingate", "Stephenville"],
  "Prince Edward Island": ["Charlottetown", "Summerside", "Stratford", "Cornwall", "Souris", "Montague", "Georgetown", "Alberton", "O'Leary", "Tignish"],

  // Australia Cities
  "New South Wales": ["Sydney", "Newcastle", "Wollongong", "Central Coast", "Canberra", "Dubbo", "Lismore", "Armidale", "Tamworth", "Orange"],
  "Queensland": ["Brisbane", "Gold Coast", "Sunshine Coast", "Cairns", "Townsville", "Toowoomba", "Mackay", "Rockhampton", "Bundaberg", "Hervey Bay"],
  "Victoria": ["Melbourne", "Geelong", "Ballarat", "Bendigo", "Shepparton", "Warrnambool", "Traralgon", "Albury", "Coleraine", "Castlemaine"],
  "Western Australia": ["Perth", "Fremantle", "Joondalup", "Bunbury", "Kalgoorlie", "Mandurah", "Albany", "Geraldton", "Broome", "Busselton"],
  "South Australia": ["Adelaide", "Mount Gambier", "Port Augusta", "Port Pirie", "Whyalla", "Port Lincoln", "Bordertown", "Orroroo", "Jamestown", "Coober Pedy"],
  "Tasmania": ["Hobart", "Launceston", "Devonport", "Burnie", "Ulverstone", "Glenorchy", "Clarence", "Tasman", "Derwent Valley", "Break O'Day"],
  "Northern Territory": ["Darwin", "Palmerston", "Alice Springs", "Katherine", "Dili", "Nhulunbuy", "Tennant Creek", "Borroloola", "Groote Eylandt", "Wadeye"],
  "Australian Capital Territory": ["Canberra", "Queanbeyan", "Wollongong", "Goulburn", "Yass", "Belconnen", "Tuggeranong", "Weston Creek", "Jerrabomberra", "Molonglo"],

  // Germany Cities
  "Bavaria": ["Munich", "Nuremberg", "Augsburg", "Ingolstadt", "Regensburg", "Würzburg", "Bamberg", "Erlangen", "Bayreuth", "Straubing"],
  "North Rhine-Westphalia": ["Cologne", "Düsseldorf", "Dortmund", "Essen", "Duisburg", "Münster", "Bochum", "Gelsenkirchen", "Aachen", "Bielefeld"],
  "Berlin": ["Berlin"],
  "Baden-Württemberg": ["Stuttgart", "Mannheim", "Karlsruhe", "Freiburg", "Heidelberg", "Ulm", "Pforzheim", "Reutlingen", "Tübingen", "Villingen-Schwenningen"],
  "Hesse": ["Frankfurt", "Wiesbaden", "Darmstadt", "Offenbach", "Hanau", "Giessen", "Kassel", "Limburg", "Bad Homburg", "Rüsselsheim"],
  "Hamburg": ["Hamburg"],
  "Lower Saxony": ["Hannover", "Braunschweig", "Osnabrück", "Oldenburg", "Göttingen", "Hildesheim", "Salzgitter", "Wolfsburg", "Wilhelmshaven", "Celle"],
  "Rhineland-Palatinate": ["Mainz", "Ludwigshafen", "Koblenz", "Trier", "Worms", "Speyer", "Kaiserslautern", "Bad Kreuznach", "Idar-Oberstein", "Neuwied"],
  "Saxony": ["Leipzig", "Dresden", "Chemnitz", "Zwickau", "Plauen", "Görlitz", "Annaberg-Buchholz", "Freiberg", "Meissen", "Bautzen"],
  "Saxony-Anhalt": ["Magdeburg", "Halle", "Dessau", "Wittenberg", "Köthen", "Stendal", "Sangerhausen", "Halberstadt", "Zeitz", "Naumburg"],
  "Schleswig-Holstein": ["Kiel", "Lübeck", "Flensburg", "Neumünster", "Rendsburg", "Bad Segeberg", "Quickborn", "Norderstedt", "Pinneberg", "Wedel"],
  "Thuringia": ["Erfurt", "Jena", "Gera", "Weimar", "Gotha", "Eisenach", "Mühlhausen", "Nordhausen", "Saalfeld", "Rudolstadt"],
  "Bremen": ["Bremen"],
  "Brandenburg": ["Potsdam", "Cottbus", "Brandenburg an der Havel", "Frankfurt (Oder)", "Prenzlau", "Bad Freienwalde", "Strausberg", "Eberswalde", "Luckenwalde", "Senftenberg"],
  "Saarland": ["Saarbrücken", "Neunkirchen", "Saarlouis", "Merzig", "St. Wendel", "Völklingen", "Homburg", "Dudweiler"],

  // France Cities
  "Île-de-France": ["Paris", "Versailles", "Boulogne-Billancourt", "Neuilly-sur-Seine", "Levallois-Perret", "Ivry-sur-Seine", "Vincennes", "Montreuil", "Créteil", "Courbevoie"],
  "Auvergne-Rhône-Alpes": ["Lyon", "Grenoble", "Saint-Étienne", "Clermont-Ferrand", "Villeurbanne", "Vaulx-en-Velin", "Annecy", "Chambéry", "Le Puy-en-Velay", "Vichy"],
  "Provence-Alpes-Côte d'Azur": ["Marseille", "Nice", "Toulon", "Aix-en-Provence", "Cannes", "Antibes", "Avignon", "Arles", "Saint-Raphaël", "La Seyne-sur-Mer"],
  "Hauts-de-France": ["Lille", "Amiens", "Roubaix", "Tourcoing", "Lens", "Dunkerque", "Arras", "Saint-Quentin", "Cambrai", "Beauvais"],
  "Nouvelle-Aquitaine": ["Bordeaux", "Toulouse", "Montauban", "Perpignan", "Bayonne", "Pau", "Agen", "Tarbes", "Angoulême", "Biarritz"],
  "Occitanie": ["Toulouse", "Montpellier", "Nimes", "Perpignan", "Albi", "Carcassonne", "Béziers", "Cahors", "Mende", "Rodez"],
  "Normandy": ["Rouen", "Le Havre", "Caen", "Amiens", "Cherbourg-en-Cotentin", "Dieppe", "Évreux", "Alençon", "Saint-Lô", "Honfleur"],
  "Brittany": ["Nantes", "Rennes", "Brest", "Lorient", "Saint-Malo", "Vannes", "Quimper", "Saint-Brieuc", "Guingamp", "Dinan"],
  "Centre-Val de Loire": ["Orléans", "Tours", "Blois", "Châteauroux", "Bourges", "Chartres", "Dreux", "Vendôme", "Amboise", "Loches"],
  "Bourgogne-Franche-Comté": ["Dijon", "Besançon", "Auxerre", "Mâcon", "Chalon-sur-Saône", "Mulhouse", "Belfort", "Montbéliard", "Nevers", "Autun"],
  "Grand Est": ["Strasbourg", "Metz", "Nancy", "Reims", "Troyes", "Thionville", "Forbach", "Épinal", "Charleville-Mézières", "Chaudfontaine"],
  "Pays de la Loire": ["Nantes", "Angers", "Le Mans", "Saint-Herblain", "Saint-Sébastien-sur-Loire", "Saint-Nazaire", "Rezé", "Guérande", "Saint-Brieuc", "Guingamp"],
  "Corsica": ["Ajaccio", "Bastia", "Corte", "Porto-Vecchio", "Calvi", "Bonifacio", "Sartène", "Propriano", "Ghisonaccia", "Algajola"],

  // UK Cities  
  "England": ["London", "Manchester", "Birmingham", "Leeds", "Sheffield", "Bristol", "Liverpool", "Newcastle", "Nottingham", "Leicester"],
  "Scotland": ["Edinburgh", "Glasgow", "Aberdeen", "Dundee", "Perth", "Stirling", "Inverness", "Ayr", "Kilmarnock", "Dunfermline"],
  "Wales": ["Cardiff", "Swansea", "Newport", "Wrexham", "Bangor", "Barry", "Neath", "Caerphilly", "Porthcawl", "Colwyn Bay"],
  "Northern Ireland": ["Belfast", "Derry", "Armagh", "Lisburn", "Newry", "Craigavon", "Ballymena", "Dungannon", "Antrim", "Ballymoney"],
};
